day16/urls.py
#from django.contrib import admin
from django.urls import path
from app01.views import depart,user,pretty,admin,account
urlpatterns = [
    #path('admin/', admin.site.urls),
    #部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),
    #用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_modelformadd),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),
    #靓号管理
    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),
    #管理员的管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),
    #登陆
    path('login/', account.login),

]

app01/models.py
from venv import create
from django.db import models

# Create your models here.[编写表结构]
class Department(models.Model):
    """部门表"""
    id=models.BigAutoField(verbose_name='ID',primary_key=True)
    title=models.CharField(verbose_name='标题',max_length=32)
    def __str__(self):
        return self.title
class UserInfo(models.Model):
    """员工表"""
    id=models.BigAutoField(verbose_name='ID',primary_key=True)
    name=models.CharField(verbose_name='姓名',max_length=16)
    password=models.CharField(verbose_name='密码',max_length=64)
    age=models.IntegerField(verbose_name='年龄')
    account=models.DecimalField(verbose_name='账户余额',max_digits=10,decimal_places=2,default=0)
    create_time=models.DateField(verbose_name='入职时间')
    #连表id并进行约束,django生成后是depart_id;
    #[删除部门，级联删除]
    depart=models.ForeignKey(verbose_name='部门',to='Department',to_field='id',on_delete=models.CASCADE)
    #[制空]
    #depart=models.ForeignKey(to='Department',to_field='id',null=True,blank=True,on_delete=models.SET_NULL)
    #在
    gender_choices=(
        (1,'男'),
        (2,'女'),
    )
    gender=models.SmallIntegerField(verbose_name='性别',choices=gender_choices)
class PrettyNum(models.Model):
    """靓号管理"""
    id=models.BigAutoField(verbose_name='ID',primary_key=True)
    mobile=models.CharField(verbose_name='手机号',max_length=11,null=True,blank=True)
    #想要允许为空，null=True,blank=True
    price=models.IntegerField(verbose_name='价格')
    level_choices=(
        (1,'1级'),
        (2,'2级'),
        (3,'3级'),
        (4,'4级'),
    )
    level=models.SmallIntegerField(verbose_name='级别',choices=level_choices,default=1)
    status_choices=(
        (1,'已占用'),
        (2,'未占用'),
    )
    status=models.SmallIntegerField(verbose_name='状态',choices=status_choices,default=1)
class Admin(models.Model):
    """管理员"""
    username=models.CharField(verbose_name='用户名',max_length=32)
    password=models.CharField(verbose_name='密码',max_length=64)
    

    

app01/views/account.py
from pyexpat import model
from django.shortcuts import render,redirect
from app01 import models
from django import forms

def login(request):
    if request.method=='GET':
        return render(request,'login.html')
    #获取用户数据   
    username=request.POST.get('user')
    password=request.POST.get('pwd')
    queryset=models.Admin.objects.all()
    
    if username=='root' and password=='123':
        return HttpResponse('登陆成功')
    #return HttpResponse('登陆失败')
    return render(request,'login.html',{'error_msg':'登陆失败'})

app01/views/admin.py
from pyexpat import model
from django.shortcuts import render,redirect
from app01 import models
from django import forms

from app01.utils.form import AdminModelForm,AdminEditModelForm,AdminResetModelForm
from app01.utils.pagination import Pagination 
# Create your views here.
def admin_list(request):
    """管理员列表"""
    #添加搜索功能
    data_dict={}
    search_data=request.GET.get('q','')
    if search_data:
        data_dict['username__contains']=search_data 
    queryset=models.Admin.objects.filter(**data_dict).order_by('-id')  
    #封装分页
    page_object=Pagination(request,queryset)    
    context={
        'queryset':page_object.page_queryset,
        'search_data':search_data,
        'page_string':page_object.html(),
    }
    return render(request,'admin_list.html',context)
def admin_add(request):
    """添加管理员"""
    title='新建管理员'
    if request.method=="GET":
        form=AdminModelForm()
        return render(request,'admin_add.html',{
            'form':form,
            'title':title
        })
    #用户POST提交数据,数据校验    
    form=AdminModelForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        #{'username':'****','password':'123','confirm_password':'333'}
        form.save()
        #重定向回管理员列表
        return redirect('/admin/list/')
    #校验失败
    return render(request,'admin_add.html',{
        'form':form,
        'title':title
    })
def admin_edit(request,nid):
    """编辑管理员"""
    #根据ID去数据库获取要编辑的那一行数据(对象)
    #对象/None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        #return redirect('/admin/list/')
        return render(request,'error.html',{'msg':'数据不存在'})
    title='编辑管理员'
    if request.method=="GET":
        form=AdminEditModelForm(instance=row_object)
        return render(request,'admin_edit.html',{
            'form':form,
            'title':title
        })
    #用户POST提交数据,数据校验
    form=AdminEditModelForm(data=request.POST,instance=row_object)
    if form.is_valid():
        form.save()
        #重定向回管理员列表
        return redirect('/admin/list/')
    #重定向回
    return render(request,'admin_edit.html',{
        'form':form,
        'title':title
    })
def admin_delete(request,nid):
    """删除管理员"""
    models.Admin.objects.filter(id=nid).delete()
    #重定向回管理员列表
    return redirect('/admin/list/')
def admin_reset(request,nid):
    """重置密码"""
    #根据ID去数据库获取要编辑的那一行数据(对象)
    #对象/None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect('/admin/list/')
        #return render(request,'error.html',{'msg':'数据不存在'})
    title='重置密码-{}'.format(row_object.username)
    if request.method=="GET":
        form=AdminResetModelForm()
        return render(request,'change.html',{
            'form':form,
            'title':title
        })
    #用户POST提交数据,数据校验
    form=AdminResetModelForm(data=request.POST,instance=row_object)
    if form.is_valid():
        form.save()
        #重定向回管理员列表
        return redirect('/admin/list/')
    #重定向回
    return render(request,'change.html',{
        'form':form,
        'title':title
    })

app01/views/depart.py
from gc import get_objects
from genericpath import exists
from pyexpat import model
from attr import field
from django.shortcuts import render,redirect
from app01 import models
from django import forms
# Create your views here.
def depart_list(request):
    """部门列表"""
    #从数据库中获取所有部门列表
    queryset=models.Department.objects.all()
    return render(request,'depart_list.html',{
        'queryset':queryset,
    })
def depart_add(request):
    """添加部门"""
    if request.method=="GET":
        return render(request,'depart_add.html')
    #获取用户POST提交过来的数据(title是否输入为空)
    title=request.POST.get('title')
    #保存到数据库
    models.Department.objects.create(title=title)
    #重定向回部门列表
    return redirect('/depart/list/')
def depart_delete(request):
    """删除部门"""
    #获取ID
    nid=request.GET.get('nid')
    #删除ID
    models.Department.objects.filter(id=nid).delete()
    #重定向回部门列表
    return redirect('/depart/list/')
def depart_edit(request,nid):
    """修改部门"""
    if request.method=="GET":
        #根据nid,获取他的数据
        row_object=models.Department.objects.filter(id=nid).first()
        return render(request,'depart_edit.html',{
            'row_object':row_object
        })
    #获取用户提交的标题
    title=request.POST.get("title")
    #根据ID找到数据库中的数据并进行更新
    models.Department.objects.filter(id=nid).update(title=title)
    #重定向回部门列表
    return redirect('/depart/list/')

app01/views/pretty.py
from gc import get_objects
from genericpath import exists
from pyexpat import model
from attr import field
from django.shortcuts import render,redirect
from app01 import models
from django import forms
from app01.utils.form import PrettyModelForm
from app01.utils.pagination import Pagination 
############靓号管理############
def pretty_list(request):
    """靓号列表"""
    #添加搜索功能
    data_dict={}
    search_data=request.GET.get('q','')
    if search_data:
        data_dict['mobile__contains']=search_data  
    #封装分页    
    queryset=models.PrettyNum.objects.filter(**data_dict).order_by('-level')
    page_object=Pagination(request,queryset)    
    context={
        'queryset':page_object.page_queryset,
        'search_data':search_data,
        'page_string':page_object.html(),
    }
    return render(request,'pretty_list.html',context)
def pretty_add(request):
    """靓号添加"""
    if request.method=="GET":
        form=PrettyModelForm()
        return render(request,'pretty_add.html',{'form':form})
    #用户POST提交数据,数据校验
    print(request.POST)
    form=PrettyModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        #重定向回部门列表
        return redirect('/pretty/list/')
    #校验失败
    return render(request,'pretty_add.html',{'form':form})
def pretty_edit(request,nid):
    """靓号修改"""
    #根据ID去数据库获取要编辑的那一行数据(对象)
    row_object=models.PrettyNum.objects.filter(id=nid).first()
    if request.method=="GET":
        form=PrettyModelForm(instance=row_object)
        return render(request,'pretty_edit.html',{'form':form})
    #用户POST提交数据,数据校验
    form=PrettyModelForm(data=request.POST,instance=row_object)
    if form.is_valid():
        form.save()
        #重定向回部门列表
        return redirect('/pretty/list/')
    #重定向回
    return render(request,'pretty_edit.html',{'form':form})
def pretty_delete(request,nid):
    """靓号删除"""
    models.PrettyNum.objects.filter(id=nid).delete()
    #重定向回部门列表
    return redirect('/pretty/list/')
############搜索手机号############
#知识点
#models.PrettyNum.objects.filter(id=12)         #id等于12
#models.PrettyNum.objects.filter(id__gt=12)     #id大于12
#models.PrettyNum.objects.filter(id__gte=12)    #id大于等于12
#models.PrettyNum.objects.filter(id__It=12)     #id小于12
#models.PrettyNum.objects.filter(id__Ite=12)    #id小于等于12

#models.PrettyNum.objects.filter(mobile='999')             #等于
#models.PrettyNum.objects.filter(mobile__startswith='999')  #筛选出以999开头
#models.PrettyNum.objects.filter(mobile__endswith='999')    #筛选出以999结尾
#models.PrettyNum.objects.filter(mobile__contains='999')    #筛选出包含999

app01/views/user.py
from gc import get_objects
from genericpath import exists
from pyexpat import model
from attr import field
from django.shortcuts import render,redirect
from app01 import models
from django import forms
from app01.utils.form import UserModelForm
def user_list(request):
    """用户列表"""
    #从数据库中获取所有用户列表
    queryset=models.UserInfo.objects.all()
    #for item in queryset:
    #    print (item.id,item.name,item.password,item.age,item.account,item.create_time.strftime("%Y-%m-%d"),item.get_gender_display(),item.depart.title)
    return render(request,'user_list.html',{
        'queryset':queryset,
    })
def user_add(request):
    """添加用户"""
    if request.method=="GET":
        context={
            'gender_choices':models.UserInfo.gender_choices,
            'depart_list':models.Department.objects.all()
        }
        return render(request,'user_add.html',context)
    #获取用户POST提交过来的数据
    user=request.POST.get('user')
    pwd=request.POST.get('pwd')
    age=request.POST.get('age')
    account=request.POST.get('ac')
    ctime=request.POST.get('ctime')
    gender_id=request.POST.get('gd')
    depart_id=request.POST.get('dp')
    #保存到数据库
    models.UserInfo.objects.create(name=user,password=pwd,age=age,account=account,create_time=ctime,gender=gender_id,depart_id=depart_id)
    #重定向回部门列表
    return redirect('/user/list/')
############ Form 示例,不针对数据库 ############
############ ModelForm 示例,针对数据库中的某个表 ############
def user_modelformadd(request):
    """添加用户(ModelForm版本)"""
    if request.method=="GET":
        form=UserModelForm()
        return render(request,'user_modelformadd.html',{'form':form})
    #用户POST提交数据,数据校验
    form=UserModelForm(data=request.POST)
    if form.is_valid():
        #如果数据合法，保存到数据库
        #print(form.cleaned_data)
        #models.UserInfo.objects.create()
        form.save()
        #重定向回部门列表
        return redirect('/user/list/')
    #校验失败
    return render(request,'user_modelformadd.html',{'form':form})
def user_edit(request,nid):
    """编辑用户"""
    #根据ID去数据库获取要编辑的那一行数据(对象)
    row_object=models.UserInfo.objects.filter(id=nid).first()
    if request.method=="GET":
        form=UserModelForm(instance=row_object)
        return render(request,'user_edit.html',{'form':form})
    #用户POST提交数据,数据校验
    form=UserModelForm(data=request.POST,instance=row_object)
    if form.is_valid():
        #如果数据合法，保存到数据库(默认保存的是用户输入的所有数据)
        #如果要保存的不是用户输入的可以用（form.instance.字段名=值）
        form.save()
        #重定向回部门列表
        return redirect('/user/list/')
    #重定向回部门列表
    return render(request,'user_edit.html',{'form':form})
def user_delete(request,nid):
    """删除部门"""
    models.UserInfo.objects.filter(id=nid).delete()
    #重定向回部门列表
    return redirect('/user/list/')

app01/templates/admin_add.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">添加管理员</div>
        <div class="panel-body">                  
            <form method='post' novalidate>
                {% csrf_token %}
                {% for field in form  %}                
                <div class="form-group">
                    <label>{{field.label}}</label>
                    {{field}}
                    <span style='color:red;'>{{field.errors.0}}</span>
                  </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提交</button>
              </form>
        </div>
    </div>
</div>
{% endblock  %}

app01/templates/admin_edit.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">编辑管理员</div>
        <div class="panel-body">                  
            <form method='post' novalidate>
                {% csrf_token %}
                {% for field in form  %}                
                <div class="form-group">
                    <label>{{field.label}}</label>
                    {{field}}
                    <span style='color:red;'>{{field.errors.0}}</span>
                  </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提交</button>
              </form>
        </div>
    </div>
</div>
{% endblock  %}

app01/templates/admin_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div style="margin-bottom:15px;">
        <a href="/admin/add/" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  新建管理员</a>
        <div class="col-lg-6" style='float: right;'> 
            <form method='get'>           
                <div class="input-group">
                    <input type="text" name="q" class="form-control" value='{{search_data}}' placeholder="Search for...">
                    <span class="input-group-btn">                    
                        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                    </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>  管理员列表</div>          
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>用户名</th>
                <th>密码</th>                
                <th>重置密码</th>          
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.username}}</td>
                    <td>{{item.password}}</td>
                    <td><a href="/admin/{{item.id}}/reset/" class='btn btn-primary btn-xs'>重置</a></td>
                    <td>
                        <a href="/admin/{{item.id}}/edit/" class='btn btn-primary btn-xs'>编辑</a>
                        <a href="/admin/{{item.id}}/delete/" class='btn btn-danger btn-xs'>删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="clearfix">
        <ul class="pagination">
            {{page_string}}
        </ul>
    </div>
</div>
{% endblock %}

app01/templates/change.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">{{title}}</div>
        <div class="panel-body">                  
            <form method='post' novalidate>
                {% csrf_token %}
                {% for field in form  %}                
                <div class="form-group">
                    <label>{{field.label}}</label>
                    {{field}}
                    <span style='color:red;'>{{field.errors.0}}</span>
                  </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提交</button>
              </form>
        </div>
    </div>
</div>
{% endblock  %}

app01/templates/depart_add.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">新建部门</div>
        <div class="panel-body">                  
            <form method='post'>
                {% csrf_token %}
                <div class="form-group">
                  <label>标题</label>
                  <input type="text" class="form-control" placeholder="标题" name="title">
                </div>
                <button type="submit" class="btn btn-primary">提交</button>
              </form>
        </div>
    </div>
</div>
{% endblock %}

app01/templates/depart_edit.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">编辑部门</div>
        <div class="panel-body">                  
            <form method='post'>
                {% csrf_token %}
                <div class="form-group">
                  <label>标题</label>
                  <input type="text" class="form-control" placeholder="标题" value={{row_object.title}} name="title">
                </div>
                <button type="submit" class="btn btn-primary">提交</button>
              </form>
        </div>
    </div>
</div>
{% endblock %}

app01/templates/depart_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div style="margin-bottom:15px;"><a href="/depart/add/" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  新建部门</a></div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>  部门列表</div>          
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.title}}</td>
                    <td>
                        <a href="/depart/{{item.id}}/edit/" class='btn btn-primary btn-xs'>编辑</a>
                        <a href="/depart/delete/?nid={{item.id}}" class='btn btn-danger btn-xs'>删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
</div>
{% endblock %}

app01/templates/error.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="alert alert-danger" role="alert">
        <strong>警告!</strong>{{msg}}
      </div>
</div>
{% endblock  %}

app01/templates/pretty_add.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">添加靓号</div>
        <div class="panel-body">                  
            <form method='post' novalidate>
                {% csrf_token %}
                {% for field in form  %}                
                <div class="form-group">
                    <label>{{field.label}}</label>
                    {{field}}
                    <span style='color:red;'>{{field.errors.0}}</span>
                  </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提交</button>
              </form>
        </div>
    </div>
</div>
{% endblock  %}

app01/templates/pretty_edit.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">编辑靓号</div>
        <div class="panel-body">                  
            <form method='post' novalidate>
                {% csrf_token %}
                {% for field in form  %}                
                <div class="form-group">
                    <label>{{field.label}}</label>
                    {{field}}
                    <span style='color:red;'>{{field.errors.0}}</span>
                  </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提交</button>
              </form>
        </div>
    </div>
</div>
{% endblock  %}

app01/templates/pretty_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div style="margin-bottom:15px;">
        <a href="/pretty/add/" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  新建靓号</a>
        <div class="col-lg-6" style='float: right;'> 
            <form method='get'>           
                <div class="input-group">
                    <input type="text" name="q" class="form-control" value='{{search_data}}' placeholder="Search for...">
                    <span class="input-group-btn">                    
                        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                    </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>  靓号列表</div>          
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>号码</th>
                <th>价格</th>
                <th>级别</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.mobile}}</td>
                    <td>{{item.price}}</td>
                    <td>{{item.get_level_display}}</td>
                    <td>{{item.get_status_display}}</td>
                    <td>
                        <a href="/pretty/{{item.id}}/edit/" class='btn btn-primary btn-xs'>编辑</a>
                        <a href="/pretty/{{item.id}}/delete/" class='btn btn-danger btn-xs'>删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="clearfix">
        <ul class="pagination">
            {{page_string}}
        </ul>
    </div>
</div>
{% endblock %}

app01/templates/user_add.html
{% extends 'layout.html' %}
{% block content %}
  <div class="container">
      <div class="panel panel-default">
          <div class="panel-heading">添加用户</div>
          <div class="panel-body">                  
              <form method='post'>
                  {% csrf_token %}
                  <div class="form-group">
                    <label>用户名</label>
                    <input type="text" class="form-control" placeholder="用户名" name="user">
                  </div>
                  <div class="form-group">
                    <label>密码</label>
                    <input type="text" class="form-control" placeholder="密码" name="pwd">
                  </div>
                  <div class="form-group">
                    <label>年龄</label>
                    <input type="text" class="form-control" placeholder="年龄" name="age">
                  </div>
                  <div class="form-group">
                    <label>余额</label>
                    <input type="text" class="form-control" placeholder="账户余额" name="ac">
                  </div>
                  <div class="form-group">
                    <label>入职时间</label>
                    <input type="text" class="form-control" id='dt' placeholder="入职时间" name="ctime">
                  </div>
                  <div class="form-group">
                    <label>性别</label>
                    <select class="form-control" name='gd'>
                      {% for item in gender_choices %}
                        <option value="{{item.0}}">{{item.1}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>部门</label>
                    <select class="form-control" name='dp'>
                      {% for item in depart_list %}
                        <option value="{{item.id}}">{{item.title}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <button type="submit" class="btn btn-primary">提交</button>
                </form>
          </div>
      </div>
  </div>
{% endblock %}

app01/templates/user_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div style="margin-bottom:15px;">
        <a href="/user/add/" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  添加用户</a>
        <a href="/user/model/form/add/" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  ModelForm添加用户</a>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>  用户列表</div>          
        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>姓名</th>
                <th>密码</th>
                <th>年龄</th>
                <th>账户余额</th>
                <th>入职时间</th>
                <th>性别</th>
                <th>部门</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.password}}</td>
                    <td>{{item.age}}</td>
                    <td>{{item.account}}</td>
                    <td>{{item.create_time|date:"y-m-d"}}</td>
                    <td>{{item.get_gender_display}}</td>
                    <td>{{item.depart.title}}</td>
                    <td>
                        <a href="/user/{{item.id}}/edit/" class='btn btn-primary btn-xs'>编辑</a>
                        <a href="/user/{{item.id}}/delete/" class='btn btn-danger btn-xs'>删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
</div>
{% endblock %}

app01/templates/user_modelformadd.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">添加用户</div>
        <div class="panel-body">                  
            <form method='post' novalidate>
                {% csrf_token %}
                {% for field in form  %}                
                <div class="form-group">
                    <label>{{field.label}}</label>
                    {{field}}
                    <span style='color:red;'>{{field.errors.0}}</span>
                  </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提交</button>
              </form>
        </div>
    </div>
</div>
{% endblock %}